main/urls.py
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter

from main import views

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'requestdeport', views.RequestDeportViewSet)
router.register(r'endpoint', views.EndPointViewSet, base_name='endpoint')
router.register(r'users', views.UserViewSet, 'users')

urlpatterns = [
    url(r'^', include(router.urls))
]

reqbucket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from main import views as mainviews
from accounts import views as account_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='main/index.html'), name='home'),
    url(r'^contact/$', mainviews.contact_view, name='contact'),
    url(r'^about/$', TemplateView.as_view(template_name='main/about.html'), name='about'),
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^jb/', include('main.urls')),
    url(r'^dashboard/$', account_views.DashBoard.as_view(), name='dashboard'),
    url(r'^api/', include('main.urls')),
]

main/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
import short_url


class EndPoint(models.Model):
    url_end = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    whos = models.ForeignKey(User, on_delete=models.CASCADE, related_name='endpoints')
    url_name = models.CharField(max_length=20, null=True)
    date_insert = models.DateTimeField(auto_now_add=True, editable=False)
    json_response = models.TextField(max_length=1000, null=True)

    def __str__(self):
        return str(short_url.encode_url(self.id))

    class Meta:
        ordering = ['-date_insert']


class RequestDeport(models.Model):
    end_point = models.ForeignKey(EndPoint, on_delete=models.CASCADE, related_name='requests')
    method = models.CharField(max_length=20, default='get')
    content_type = models.CharField(max_length=100)
    content_length = models.IntegerField(null=True)
    remote_address = models.CharField(max_length=30, null=True)
    http_user_agent = models.CharField(max_length=256, null=True)
    body = models.CharField(max_length=256, null=True)
    content_params = models.CharField(max_length=100, null=True)
    COOKIES = models.TextField(null=True)
    date_insert = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.end_point)

    def save(self, *args, **kwargs):
        import pdb; pdb.set_trace()
        super(RequestDeport, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-date_insert']

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "cdn/bootstrap-3.3.7-dist/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "cdn/bootstrap-3.3.7-dist/css/bootstrap-theme.css" %}">
    <!-- Latest compiled and minified CSS -->
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"#}
    {#          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}

    <!-- Optional theme -->
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"#}
    {#          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">#}
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">#}
    <link rel="stylesheet" href="{% static "css/edit.css" %}">
    <title>{% block title %}Request Bucket{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Request Bucket</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li {% if request.path == home %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
                <li {% if request.path == results %}class="active"{% endif %}><a
                        href="{% url 'dashboard' %}">Dashboard</a></li>
                <li {% if request.path == about %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>
                <li {% if request.path == contact %}class="active"{% endif %}><a href="{% url 'contact' %}">Contact
                    Us</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'account_signup' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a>
                    </li>
                    <li><a href="{% url 'account_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a>
                    </li>
                {% else %}
                    <li><a href="{% url 'account_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Log
                        Out</a></li>
                    <li><a>Logged in as {{ user.username }}</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <noscript>
        <h3 style="color:red"> This site requires javascript to work properly. please activate</h3>
    </noscript>
    {% block content %}{% endblock %}
</div>
<footer>
    <div class="align-content-md-center small">
        ReqBucket is optimized for learning and testing. <br> We cannot warrant full correctness of all content.<br>
        While using this site, you agree to have read and accepted our <a href="#">terms of
        use</a>,
        <a href="#">cookie and privacy policy</a>.
        <a href="#">Copyright 2017</a> by Refsnes Data. All Rights Reserved.<br>
        <a href="#">Powered by django</a>.<br><br>
        <a href="#"></a>
        {#    <img style="width:150px;height:28px;border:0" src="{% static 'file_search.png' %}" alt="putsreq.com"></a>#}
    </div>

</footer>
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"#}
{#        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"#}
{#        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="{% static "js/results_js.js" %}"></script>#}
<script rel="script" src="{% static "cdn/jquery-3.2.1.min.js" %}"></script>
{#<script rel="script" src="{% static "js/popper.min.js" %}"></script>#}
<script rel="script" src="{% static "cdn/bootstrap-3.3.7-dist/js/bootstrap.js" %}"></script>
<script rel="script" src="{% static "js/results_js.js" %}"></script>
<script rel="script" src="{% static "mustache.js-master/mustache.js" %}"></script>
<script rel="script" src="{% static "js/stretchy.js" %}" data-filter="#id_json_response" async></script>
</body>
</html>